### ISSUE TITLE
Access to XMLHttpRequest has been blocked by CORS policy

### ISSUE THREAD

**Issue by Adelina122** [sreeshilck/CRUD-user-management-react#1]
Hi, I tried to fork your project and follow your instructions, but I keep facing the same problem:
`Access to XMLHttpRequest at 'http://localhost:4000/register' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.` 
How do I solve it?

**Comment by sreeshilck** [comment]
Hi @Adelina122 ,

Thank you for letting me know about the issue. I've updated the server configuration to allow requests from `http://localhost:3000`. The fix has been pushed to the repository. The CORS issue should now be resolved.

To ensure that the fix is applied, please pull the latest changes from the repository to your local environment:

`git pull origin master
`

If you have any further questions or encounter any issues, please feel free to let me know.
